version: '3.8'

services:
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    container_name: lde.redis
    ports:
      - 6380:6379
  order.api:
    container_name: lde.order.api
    build:
      context: .
      dockerfile: Order/Order.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5006
       - ConnectionString=server=postgres;port=5432;database=catalog;uid=postgres;password=postgres;
       - CdnHost=http://www.petshop.com:81
       - PathBase=http://www.petshop.com:5006
       - CatalogBffUrl=http://www.petshop.com:5000/api/v1/CatalogBff
       - CatalogItemUrl=http://www.petshop.com/api/v1/CatalogItem
    depends_on:
      - catalog.api
      - identityserver
    ports:
      - 5006:5006
  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.petshop.com:5002
      - Redis__Host=www.petshop.com:6380
      - Redis__CacheTimeout=00:30:00
      - PathBase=http://www.petshop.com:5003
      - OrderUrl=http://www.petshop.com:5006/api/v1/OrderBff
    depends_on:
      - redis
    ports:
      - 5003:5003
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - ConnectionString=server=postgres;port=5432;database=catalog;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.petshop.com:5002
       - PathBase=http://www.petshop.com:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000
  web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: Web/MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogUrl=http://www.petshop.com:5000/api/v1/CatalogBff
      - BasketUrl=http://www.petshop.com:5003/api/v1/basketbff
      - Authorization__Authority=http://www.petshop.com:5002
      - IdentityUrl=http://www.petshop.com:5002
      - CallBackUrl=http://www.petshop.com:81/
      - RedirectUri=http://www.petshop.com:81/signin-oidc
    depends_on:
      - catalog.api
      - identityserver
      - basket.api
    ports:
      - 5001:5001
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.petshop.com:81
      - CatalogApi=http://www.petshop.com:5000
      - BasketApi=http://www.petshop.com:5003
    ports:
      - 5002:5002
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 81:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80 

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 194.168.0.0/24
          gateway: 194.168.0.1